db: 
  environment: 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=bugtracker
    - MYSQL_USER=mantisbt
    - MYSQL_PASSWORD=mantisbt
  image: mariadb
  ports: 
    - "3306:3306"
  restart: always

mantisbt: 
  image: "vimagick/mantisbt:latest"
  links: 
    - db
  ports: 
    - "8989:80"
  restart: always

selenium-hub:
  image: selenium/hub
  container_name: selenium-hub
  ports:
    - "4444:4444"
  environment:
    - GRID_TIMEOUT=15
    - GRID_BROWSER_TIMEOUT=15
    - GRID_MAX_SESSION=2
  restart: always
  
chrome:
  image: selenium/node-chrome
  links: 
    - selenium-hub
  environment:
    - HUB_HOST=selenium-hub
    - HUB_PORT=4444
    - SCREEN_WIDTH=1920
    - SCREEN_HEIGHT=1080
    - SCREEN_DEPTH=24
  restart: always
  
firefox:
  image: selenium/node-firefox
  links: 
    - selenium-hub
  environment:
    - HUB_HOST=selenium-hub
    - HUB_PORT=4444
    - SCREEN_WIDTH=1920
    - SCREEN_HEIGHT=1080
    - SCREEN_DEPTH=24
  restart: always

jenkins:
  image: jenkins/jenkins:lts
  privileged: true
  restart: always
  ports:
    - "80:8080"
    - "50000:50000"
  Volumes:
    - jenkins-data:/var/jenkins_home/
    - /var/run/docker.sock:/var/run/docker.sock
    - /home/desafiobase2/ .docker/:/home/jenkins/ .docker/
    - /home/test